apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: petclinic-dev
  labels:
    app: customers-service
    tier: backend
    app.kubernetes.io/name: customers-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: customers-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---