apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petclinic-prod

resources:
  - ../../base/config-server/
  - ../../base/discovery-server/
  - ../../base/api-gateway/
  - ../../base/customers-service/
  - ../../base/visits-service/
  - ../../base/vets-service/
  - ../../base/genai-service/
  - ../../base/admin-server/
  - ./external-secrets/
  - hpa.yaml
  - pdb.yaml

replicas:
  - name: config-server
    count: 2
  - name: discovery-server
    count: 2
  - name: api-gateway
    count: 2
  - name: customers-service
    count: 2
  - name: visits-service
    count: 2
  - name: vets-service
    count: 2
  - name: genai-service
    count: 1
  - name: admin-server
    count: 1