apiVersion: v1
kind: ServiceAccount
metadata:
  name: vets-service-sa
  namespace: petclinic-dev
  labels:
    app.kubernetes.io/name: vets-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm