apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-server-sa
  namespace: petclinic-dev
  labels:
    app: admin-server
    component: admin
    app.kubernetes.io/name: admin-server
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
---