apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: rds-credentials
    namespace: petclinic-prod
    labels:
        app.kubernetes.io/name: rds-credentials
        app.kubernetes.io/part-of: petclinic
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/component: infrastructure
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: ClusterSecretStore
        name: aws-secrets-manager
    target:
        name: rds-credentials
        creationPolicy: Owner
    data:
        - secretKey: SPRING_DATASOURCE_USERNAME
          remoteRef:
              key: petclinic/prod/rds-credentials
              property: username
        - secretKey: SPRING_DATASOURCE_PASSWORD
          remoteRef:
              key: petclinic/prod/rds-credentials
              property: password
