apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: petclinic-dev
  labels:
    app: api-gateway
    component: gateway
    tier: frontend
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Hel