apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery-server-sa
  namespace: petclinic-dev
  labels:
    app: discovery-server
    app.kubernetes.io/name: discovery-server
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
---